# Generated by Django 2.2.1 on 2019-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_field',
            new_name='content',
        ),
    ]
