# Generated by Django 2.2.1 on 2019-05-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190502_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_modefied',
            new_name='last_modified',
        ),
    ]
