# Generated by Django 3.0.1 on 2020-01-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191121_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
